server:
  port: 8081

stats-server:
  url: http://localhost:9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_main_db
    username: ewm_user
    password: ewm_password
logging:
  level:
    root: INFO
    ru.practicum.explorewithme.main: DEBUG